### ISSUE TITLE
questions about feihand dataset

### ISSUE THREAD

**Issue by yanglilian** [moranli-aca/LearnableGroups-Hand#4]
Could you release the loader file of the freihand dataset and publish the training config? thank you

**Comment by moranli-aca** [comment]
Thanks for your attention~!!

For the FreiHand dataset loader code, we refer to the [FreiHand Repo](https://github.com/lmb-freiburg/freihand). And the training details of our method are contained in the main paper, you can follow that~~.

Feel free to contact me via moranli.aca@gamil.com if your meet any questions  during your training on the FreiHand dataset~~
